# amulog example: classify the OpenSSH 2k sample with the bundled amulog
# templates (OpenSSH.tpl) instead of generating them.
#   python -m amulog db-make -c config_import.conf

[general]
src_path = OpenSSH_2k.log
src_recur = false
logging =

[database]
database = sqlite3
sqlite3_filename = log.db

[manager]
parser_script = parser.py

[log_template]
lt_methods = import
ltgroup_alg = none

[log_template_import]
def_path = OpenSSH.tpl
import_format = plain
search_method = tree
